"""Initial escrow marketplace schema

Revision ID: 2a7266336c68
Revises: 
Create Date: 2026-07-03 22:44:33.726583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7266336c68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('ticket_phases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('face_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'SOLD_OUT', name='ticket_phase_status'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_ticket_phases_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_phases')),
    sa.UniqueConstraint('event_id', 'slug', name='uq_ticket_phases_event_id_slug')
    )
    op.create_index(op.f('ix_ticket_phases_event_id'), 'ticket_phases', ['event_id'], unique=False)
    op.create_table('wishlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_wishlist_items_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wishlist_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wishlist_items')),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_wishlist_items_user_id_event_id')
    )
    op.create_index(op.f('ix_wishlist_items_event_id'), 'wishlist_items', ['event_id'], unique=False)
    op.create_index(op.f('ix_wishlist_items_user_id'), 'wishlist_items', ['user_id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('ticket_phase_id', sa.UUID(), nullable=False),
    sa.Column('asking_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('external_ticket_identifier', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESERVED', 'SOLD', 'CANCELLED', name='listing_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_listings_seller_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_phase_id'], ['ticket_phases.id'], name=op.f('fk_listings_ticket_phase_id_ticket_phases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listings'))
    )
    op.create_index(op.f('ix_listings_seller_id'), 'listings', ['seller_id'], unique=False)
    op.create_index(op.f('ix_listings_ticket_phase_id'), 'listings', ['ticket_phase_id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ticket_phase_id', sa.UUID(), nullable=False),
    sa.Column('max_budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_phase_id'], ['ticket_phases.id'], name=op.f('fk_waitlist_entries_ticket_phase_id_ticket_phases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_waitlist_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waitlist_entries')),
    sa.UniqueConstraint('user_id', 'ticket_phase_id', name='uq_waitlist_entries_user_id_ticket_phase_id')
    )
    op.create_index(op.f('ix_waitlist_entries_ticket_phase_id'), 'waitlist_entries', ['ticket_phase_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_user_id'), 'waitlist_entries', ['user_id'], unique=False)
    op.create_table('escrow_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('buyer_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('seller_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ESCROWED', 'VERIFIED', 'RELEASED', 'EXPIRED', 'REFUNDED', name='escrow_transaction_status'), nullable=False),
    sa.Column('transfer_code', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_escrow_transactions_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], name=op.f('fk_escrow_transactions_listing_id_listings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('fk_escrow_transactions_seller_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escrow_transactions'))
    )
    op.create_index(op.f('ix_escrow_transactions_buyer_id'), 'escrow_transactions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_listing_id'), 'escrow_transactions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_seller_id'), 'escrow_transactions', ['seller_id'], unique=False)
    op.create_index(op.f('ix_escrow_transactions_status'), 'escrow_transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escrow_transactions_status'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_seller_id'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_listing_id'), table_name='escrow_transactions')
    op.drop_index(op.f('ix_escrow_transactions_buyer_id'), table_name='escrow_transactions')
    op.drop_table('escrow_transactions')
    op.drop_index(op.f('ix_waitlist_entries_user_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_ticket_phase_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_listings_ticket_phase_id'), table_name='listings')
    op.drop_index(op.f('ix_listings_seller_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_wishlist_items_user_id'), table_name='wishlist_items')
    op.drop_index(op.f('ix_wishlist_items_event_id'), table_name='wishlist_items')
    op.drop_table('wishlist_items')
    op.drop_index(op.f('ix_ticket_phases_event_id'), table_name='ticket_phases')
    op.drop_table('ticket_phases')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
