"""Add events listings scraper sources

Revision ID: dd1295b6fe9b
Revises: 2b993b4761dd
Create Date: 2026-07-04 09:46:07.320311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1295b6fe9b'
down_revision: Union[str, Sequence[str], None] = '2b993b4761dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('robots_txt_status', sa.Enum('ALLOWED', 'DISALLOWED', 'UNCLEAR', name='robots_txt_status'), nullable=False),
    sa.Column('tos_status', sa.Enum('PROHIBITS_SCRAPING', 'SILENT', 'ALLOWS', 'UNCLEAR', name='tos_status'), nullable=False),
    sa.Column('has_public_api', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_currently_approved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scraper_sources')),
    sa.UniqueConstraint('site_name', name=op.f('uq_scraper_sources_site_name'))
    )
    op.add_column('events', sa.Column('source_site', sa.String(length=120), nullable=True))
    op.add_column('events', sa.Column('external_event_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_source_site'), 'events', ['source_site'], unique=False)
    op.create_unique_constraint('uq_events_source_site_external_event_id', 'events', ['source_site', 'external_event_id'])
    op.add_column('ticket_phases', sa.Column('estimated_gate_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('users', 'is_admin', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('ticket_phases', 'estimated_gate_value')
    op.drop_constraint('uq_events_source_site_external_event_id', 'events', type_='unique')
    op.drop_index(op.f('ix_events_source_site'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_column('events', 'external_event_id')
    op.drop_column('events', 'source_site')
    op.drop_table('scraper_sources')
    # ### end Alembic commands ###
